config/routes.rb
Wakandacasts::Application.routes.draw do
  root :to => "episodes#index"

  match "auth/:provider/callback" => "users#create"
  match "about" => "info#about", :as => "about"
  match "give_back" => "info#give_back", :as => "give_back"
  match "moderators" => "info#moderators", :as => "moderators"
  match "login" => "users#login", :as => "login"
  match "logout" => "users#logout", :as => "logout"
  match "feedback" => "feedback_messages#new", :as => "feedback"
  match "episodes/archive" => redirect("/?view=list")
  match 'unsubscribe/:token' => 'users#unsubscribe', :as => "unsubscribe"
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :users do
    member { put :ban }
  end
  resources :comments
  resources :episodes
  resources :feedback_messages

  match "tags/:id" => redirect("/?tag_id=%{id}")
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end

  def give_back
  end
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/about.html.erb
<% title "About RailsCasts", false %>

<div class="content" id="about">
  <div class="ryan">
    <%= image_tag "ryan_bates.jpg", :size => "192x227" %>
    <a href="http://twitter.com/rbates">Ryan Bates</a>
  </div>
  <h1>About RailsCasts</h1>
  <p>RailsCasts is produced by Ryan Bates (<%= link_to "rbates", "http://twitter.com/rbates" %> on Twitter and <%= link_to "ryanb", "https://github.com/ryanb" %> on GitHub). A new episode will be released each Monday featuring tips and tricks with <a href="http://www.rubyonrails.com/">Ruby on Rails</a>. The screencasts are short and focus on one technique so you can quickly move on to applying it to your own project. The topics target the intermediate Rails developer, but beginners and experts will get something out of it as well.</p>

  <h2>ASCIIcasts</h2>
  <p>If you prefer text over video, please visit <%= link_to "ASCIIcasts", "http://asciicasts.com/" %> where Eifion Bedford has done a wonderful job of translating the majority of the episodes into textual form.</p>

  <h2>TextMate Theme</h2>
  <p>Do you like the TextMate theme used in these screencasts? It is custom made and based off of the theme by <a href="http://fluidsyntax.com/blog/articles/idlefingers-textmate-theme">idlefingers</a>. I am using the <a href="http://www.gnome.org/fonts/">Bitstream Vera Sans Mono</a> font.</p>
  <p><a href="http://media.railscasts.com/resources/textmate_theme.zip">Download Textmate Theme</a></p>

  <h2>Contact</h2>
  <p>If you have any comments, suggestions, questions, etc. I'd love to hear them! Please use the <%= link_to "Feedback Page", feedback_path %> or send an email to <script type="text/javascript">document.write(
"<n uers=\"znvygb:srrqonpx\100envyfpnfgf\056pbz\">srrqonpx\100envyfpnfgf\056pbz<\057n>".replace(/[a-zA-Z]/g, function(c){return String.fromCharCode((c<="Z"?90:122)>=(c=c.charCodeAt(0)+13)?c:c-26);}));
</script>.</p>

  <h2>Moderators</h2>
  <p>Thank you to all moderators who help keep the site clean and up to date:</p>
  <ul>
    <% for user in User.where(:moderator => true).order(:name) %>
      <li><%= link_to user.name, user %></li>
    <% end %>
  </ul>
  <p>If you are interested in becoming a moderator, see the <%= link_to "moderator guidelines", moderators_path %>.</p>

  <h2>Special Thanks</h2>
  <p>Special thanks to <%= link_to "Linode", "http://www.linode.com/?utm_source=railscasts.com&utm_medium=Badge&utm_campaign=Railscasts" %> for providing hosting for this site and <%= link_to "SublimeVideo", "http://sublimevideo.net/" %> for providing the episode player.</p>

  <h2>This Site</h2>
  <p>This site is available in <%= link_to "open source", "https://github.com/ryanb/railscasts" %>. It is intended to be used as an example Rails app, so feel free to copy bits of it for your own project. If you would like to use it as a starting point for your own site please contact me.</p>

  <h2>Software Used</h2>
  <ul>
    <li><a href="http://macromates.com/">TextMate</a> - the best text editor</li>
    <li><a href="http://stephendeken.net/software/keycastr/">KeyCastr</a> - visual keyboard shortcuts</li>
    <li><a href="http://shinywhitebox.com/home/home.html">iShowU</a> - records the screen</li>
    <li><a href="http://www.apple.com/finalcutpro/">Final Cut Pro</a> - for putting it all together</li>
    <li><a href="http://www.apple.com/motion/">Motion</a> - the intro animation</li>
  </ul>

  <h2>License</h2>
  <p>All RailsCasts episodes are under the <a href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/">Creative Commons license</a>. You are free to distribute unedited versions of the episodes for non-commercial purposes. You are also free to translate them into any language. If you would like to edit the video please contact me.</p>
  <p><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/3.0/us/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-nd/3.0/us/88x31.png" /></a></p>
</div>

app/views/info/give_back.html.erb
<% title "Give Back to Open Source", false %>

<div class="content">
  <%= image_tag "give_back.jpg", :size => "158x60", :id => "give_back" %>
  <p>A lot of effort is put into open source software which is given away for free. In <%= link_to "Episode 200", episode_path(200) %> I am challenging everyone to give back to the open source community.</p>
  <div id="give_back_instructions">
    <p><strong>Here's what I want you to do:</strong></p>
    <ol>
      <li>Look in your biggest Rails project</li>
      <li>Go through every gem and plugin used</li>
      <li>
        Contribute back to each by:
        <ul>
          <li>Making a donation</li>
          <li>Fixing a bug</li>
          <li>Adding documentation</li>
          <li>Or simply thanking them</li>
        </ul>
      </li>
    </ol>
  </div>
  <p>Make a difference and give back to open source!</p>
</div>

app/views/info/moderators.html.erb
<% title "Moderator Guidelines" %>

<div class="content" id="moderators">
  <p><strong>Thank you to all who are interested in becoming moderators. I currently have enough moderators but may need more in the future.</strong> You can still request to become a moderator, and I will consider it when a position is available.</p>

  <p>Moderators primarily help deal with the spam issues, but also help fix show notes and review unreleased episodes. If you are interested in becoming a moderator, <%= link_to "let me know", feedback_path %> and provide reasons as to why you should become one along with your GitHub username.</p>

  <h2>Editing User Comments</h2>
  <p>Moderators are able to edit user comments. This is intended to fix incorrect formatting. Do not alter what the user is saying. If you must add a note, ensure that it is clearly marked as edited by you.</p>

  <h2>Deleting User Comments</h2>
  <p>Comments can be removed if they provide no value to the conversation, are offensive, or are spam. <strong>Do not delete comments which have replies</strong>, instead edit them to remove the content and include a note saying it has been removed by a moderator. If a comment is a simple "thank you" and is over a month old, feel free to delete it.</p>

  <h2>Banning Users</h2>
  <p>Users can be banned. When this happens all of their comments will be deleted and they will be unable to add further comments. Users who are spamming the site should be banned. Banning users is not available on older comments because a user account system was not available then. You will need to delete those individually.</p>
  <p>If you are ever uncertain whether it is spam or not, click on their profile and read their other comments. If you are still unsure, leave it alone. We do not want to ban legitimate users.</p>
  <p>Both banning users and deleting comments have a confirmation dialog, so don't worry too much about accidentally hitting the button. If you do accidentally delete a comment or ban a user, let me know immediately and provide as much detail as you can.</p>
  <p>If at any time I find a moderator not following these guidelines I will remove the privilege and revert all actions he has done. A paper trail of all changes are kept.</p>

  <h2>Reviewing Unreleased Episodes</h2>
  <p>On the rare occasion I finish recording an episode early, it will show up on the front page for moderators before it is released. Feel free to watch this and provide feedback if you find problems. Please send feedback through email or the <%= link_to "feedback page", feedback_path %>, not the comments section until the episode is released.</p>

  <h2>Editing Episode Show Notes</h2>
  <p>Moderators can edit episode show notes. Feel free to add notes based on what users mention in the comments. Also please include links to related episodes, mention problems with specific Rails versions, fix minor problems with the source code, etc. If you are doing significant changes to the show notes, please ask me first.</p>

  <h2>Special Thanks</h2>
  <p>Thank you to all who are interested in becoming moderators. I am very grateful to all who can help clean up the site and make it better. Your name will appear in a moderators list in the <%= link_to "About page", about_path %> for credit. If you are interested in becoming a moderator, <%= link_to "let me know", feedback_path %> and provide reasons as to why you should become one along with your GitHub username.</p>
  <p>If you have ideas on how I can improve the moderator experience, please add an issue to the <%= link_to "GitHub project", "https://github.com/ryanb/railscasts" %>.</p>
</div>